services:
#  shop:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: no
#    ports:
#      - "8000:8000"
#    command: >
#      sh -c "python manage.py migrate &&
#             python manage.py runserver 0.0.0.0:8000"
#    depends_on:
#    - postgres
#    healthcheck:
#      test: curl --fail http://localhost:8000 || exit 1
#      interval: 10s
#      timeout: 10s
#      start_period: 10s
#      retries: 3
#    env_file:
#    - ./.env

  postgres:
    image: "postgres:14-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=User
      - POSTGRES_PASSWORD=Password
      - POSTGRES_DB=db
    env_file:
      - ./.env
    volumes:
      - ./database-data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    restart: "always"
    ports:
      - "6379:6379"