# Generated by Django 5.0.6 on 2024-07-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_company_options_alter_productorder_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ("name",), "verbose_name_plural": "companies"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterModelOptions(
            name="productorder",
            options={
                "default_related_name": "product_orders",
                "ordering": ("order",),
                "verbose_name_plural": "product orders",
            },
        ),
    ]
